const Datas = [
    {
        id: 6,
        name: "Chicken Manchurian",
        description: "Boneless",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/gew7xri7af3rfwxrv2yg",
        price: 320.0,
        type: "Non Veg",
        rating: "4.4",
        nutrition: {
            calories: 280,
            protein: 22,
            carbs: 20,
            sugars: 8,
            fiber: 3,
            fat: 12,
            saturatedFat: 3,
            transFat: 0,
            cholesterol: 60,
            sodium: 800,
            potassium: 350,
            vitaminA: 8,
            vitaminC: 20,
            calcium: 4,
            iron: 10
        }
    },
    {
        id: 4,
        name: "Hyderabadi Butter Chicken Masala",
        description: "Spicy",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/37ca011bce9c1a31e363f1918f183cc5",
        price: 360.0,
        type: "Non Veg",
        rating: "4.2",
        nutrition: {
            calories: 340,
            protein: 25,
            carbs: 18,
            sugars: 6,
            fiber: 2,
            fat: 18,
            saturatedFat: 5,
            transFat: 0,
            cholesterol: 70,
            sodium: 700,
            potassium: 300,
            vitaminA: 12,
            vitaminC: 15,
            calcium: 5,
            iron: 12
        }
    },
    {
        id: 3,
        name: "Hyderabadi Chicken Biryani",
        description: "Indian,Hyderabadi",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ezggcossyzckez3mdr5o",
        price: 299.0,
        type: "Non Veg",
        rating: "4.5",
        nutrition: {
            calories: 400,
            protein: 30,
            carbs: 50,
            sugars: 5,
            fiber: 4,
            fat: 12,
            saturatedFat: 3,
            transFat: 0,
            cholesterol: 75,
            sodium: 750,
            potassium: 400,
            vitaminA: 10,
            vitaminC: 10,
            calcium: 6,
            iron: 15
        }
    },
    {
        id: 8,
        name: "Chicken Lollypop (dry)",
        description: "Crispy and Spicy",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/37ca011bce9c1a31e363f1918f183cc5",
        price: 139.0,
        type: "Non Veg",
        rating: "4.4",
        nutrition: {
            calories: 250,
            protein: 20,
            carbs: 10,
            sugars: 3,
            fiber: 1,
            fat: 15,
            saturatedFat: 3,
            transFat: 0,
            cholesterol: 65,
            sodium: 600,
            potassium: 250,
            vitaminA: 6,
            vitaminC: 8,
            calcium: 3,
            iron: 8
        }
    },
    {
        id: 5,
        name: "Chettinadu Chicken Gravy",
        description: "Hyderabadi Style",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/7ef9ea48e61c5893cd1180c25cb8988f",
        price: 340.0,
        type: "Non Veg",
        rating: "4.4",
        nutrition: {
            calories: 320,
            protein: 24,
            carbs: 15,
            sugars: 6,
            fiber: 3,
            fat: 18,
            saturatedFat: 4,
            transFat: 0,
            cholesterol: 70,
            sodium: 700,
            potassium: 300,
            vitaminA: 10,
            vitaminC: 15,
            calcium: 4,
            iron: 10
        }
    },
    {
        id: 2,
        name: "Pepper Chicken",
        description: "Dry and Bony",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/c11cfc62f993a5bdd3bcb680f1779a8f",
        price: 350.0,
        type: "Non Veg",
        rating: "4.4",
        nutrition: {
            calories: 270,
            protein: 23,
            carbs: 12,
            sugars: 4,
            fiber: 2,
            fat: 14,
            saturatedFat: 3,
            transFat: 0,
            cholesterol: 65,
            sodium: 650,
            potassium: 300,
            vitaminA: 8,
            vitaminC: 10,
            calcium: 4,
            iron: 9
        }
    },
    {
        id: 1,
        name: "Chicken 65",
        description: "Boneless",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/8b7d6fa4c03ea01eac5146bd1df92d4c",
        price: 170.0,
        type: "Non Veg",
        rating: "4.3",
        nutrition: {
            calories: 240,
            protein: 21,
            carbs: 10,
            sugars: 3,
            fiber: 1,
            fat: 12,
            saturatedFat: 2,
            transFat: 0,
            cholesterol: 60,
            sodium: 600,
            potassium: 250,
            vitaminA: 6,
            vitaminC: 8,
            calcium: 3,
            iron: 8
        }
    },
    {
        id: 7,
        name: "Hyderabadi Mutton Biryani",
        description: "Indian,Hyderabadi",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/qbfotqlcwc9hz0h8lswz",
        price: 399.0,
        type: "Non Veg",
        rating: "4.5",
        nutrition: {
            calories: 450,
            protein: 35,
            carbs: 50,
            sugars: 5,
            fiber: 5,
            fat: 15,
            saturatedFat: 4,
            transFat: 0,
            cholesterol: 80,
            sodium: 800,
            potassium: 450,
            vitaminA: 12,
            vitaminC: 12,
            calcium: 7,
            iron: 16
        }
    },
    {
        id: 16,
        name: "Banana Smoothie Bowl",
        description: "Filling and post workout bowl. fresh made with pure fruits and natural | no added sugar | | vegan |choice of vegan milk + banana + dates blended together",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/65db3f8fd70b360399a78992e925b176",
        price: 219.0,
        type: "veg",
        rating: "3.9",
        nutrition: {
            calories: 210,
            protein: 3,
            carbs: 50,
            sugars: 30,
            fiber: 5,
            fat: 1,
            saturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
            sodium: 5,
            potassium: 400,
            vitaminA: 10,
            vitaminC: 15,
            calcium: 8,
            iron: 2
        }
    },
    {
        id: 17,
        name: "Radiate Fruit Bowl",
        description: "For a glowing skin dairy free | vegan | apple + kiwi + Mango + pomegranate",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/cd7668522904b38902b1568add7792fb",
        price: 190.0,
        type: "veg",
        rating: "4.0",
        nutrition: {
            calories: 180,
            protein: 2,
            carbs: 40,
            sugars: 25,
            fiber: 6,
            fat: 0.5,
            saturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
            sodium: 10,
            potassium: 300,
            vitaminA: 12,
            vitaminC: 30,
            calcium: 6,
            iron: 1
        }
    },
    {
        id: 9,
        name: "Cold Pressed Pomegranate",
        description: "Pomegranate and juicy",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/f041578dd2fc615e9c624acd81d2a0af",
        price: 220.0,
        type: "veg",
        rating: "4.9",
        nutrition: {
            calories: 120,
            protein: 1,
            carbs: 30,
            sugars: 20,
            fiber: 2,
            fat: 0,
            saturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
            sodium: 10,
            potassium: 200,
            vitaminA: 6,
            vitaminC: 25,
            calcium: 4,
            iron: 1
        }
    },
    {
        id: 13,
        name: "Mixed Berry Smoothie Bowl",
        description: "Fresh made with pure fruits and natural | no added sugar | | vegan | choice of vegan milk + strawberry + blue berry + black berry + dates blended together",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/3ce4c5de7fc4a98cce7ce5e863ef64c2",
        price: 380.0,
        type: "veg",
        rating: "4.4",
        nutrition: {
            calories: 250,
            protein: 4,
            carbs: 55,
            sugars: 30,
            fiber: 8,
            fat: 2,
            saturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
            sodium: 15,
            potassium: 350,
            vitaminA: 8,
            vitaminC: 35,
            calcium: 10,
            iron: 3
        }
    },
    {
        id: 15,
        name: "Fruit Bowl",
        description: "Construct your own fruit bowl with your favorite fruits",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/4c4905d32b82b5b8f380c088e6901971",
        price: 10.0,
        type: "veg",
        rating: "4.9",
        nutrition: {
            calories: 100,
            protein: 1,
            carbs: 25,
            sugars: 15,
            fiber: 3,
            fat: 0.5,
            saturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
            sodium: 5,
            potassium: 200,
            vitaminA: 5,
            vitaminC: 20,
            calcium: 4,
            iron: 1
        }
    },
    {
        id: 12,
        name: "Energy Fruit Bowl",
        description: "Grab a bowl for energy | vegan | | no sugar | watermelon + papaya + apple + banana",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/4d9c886100d52a3ca04558a462625739",
        price: 190.0,
        type: "veg",
        rating: "4.7",
        nutrition: {
            calories: 200,
            protein: 2,
            carbs: 50,
            sugars: 20,
            fiber: 4,
            fat: 1,
            saturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
            sodium: 10,
            potassium: 350,
            vitaminA: 10,
            vitaminC: 25,
            calcium: 6,
            iron: 2
        }
    },
    {
        id: 18,
        name: "Choco Peanut Butter Smoothie Bowl",
        description: "Fresh made with pure fruits and natural | no added sugar | | vegan | choice of vegan milk + peanut butter + chocolate + banana",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/ef87d8ccb0f56d4e0e224324ccc6fc6a",
        price: 279.0,
        type: "veg",
        rating: "4.2",
        nutrition: {
            calories: 300,
            protein: 6,
            carbs: 50,
            sugars: 20,
            fiber: 4,
            fat: 10,
            saturatedFat: 2,
            transFat: 0,
            cholesterol: 0,
            sodium: 15,
            potassium: 400,
            vitaminA: 8,
            vitaminC: 15,
            calcium: 10,
            iron: 3
        }
    },
    {
        id: 10,
        name: "Wonder Women Fruit Bowl",
        description: "A combination of fruits to get glowing skin and to rejuvenate your body | new | chef's special | |date",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/cd7668522904b38902b1568add7792fb",
        price: 280.0,
        type: "veg",
        rating: "4.5",
        nutrition: {
            calories: 220,
            protein: 3,
            carbs: 50,
            sugars: 25,
            fiber: 6,
            fat: 2,
            saturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
            sodium: 10,
            potassium: 350,
            vitaminA: 12,
            vitaminC: 30,
            calcium: 8,
            iron: 2
        }
    },
    {
        id: 14,
        name: "Mango Smoothie Bowl",
        description: "Fresh made with pure fruits and natural | no added sugar | | vegan |choice of vegan milk + mango + banana + dates grinded",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/0a96eec5d7811f21846fdf8e5e7e79a8",
        price: 300.0,
        type: "veg",
        rating: "3.8",
        nutrition: {
            calories: 240,
            protein: 3,
            carbs: 60,
            sugars: 30,
            fiber: 5,
            fat: 1,
            saturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
            sodium: 10,
            potassium: 400,
            vitaminA: 20,
            vitaminC: 30,
            calcium: 10,
            iron: 2
        }
    },
    {
        id: 11,
        name: "Chicken Burger",
        description: "Crumb Fried Chicken Patty Topped With Lots Of In House Mayonnaise",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/ea9da8c54b5a0b3a6c3f5ea9f00a2ef6",
        price: 220.0,
        type: "Non Veg",
        rating: "4.2",
        nutrition: {
            calories: 350,
            protein: 15,
            carbs: 45,
            sugars: 10,
            fiber: 2,
            fat: 15,
            saturatedFat: 5,
            transFat: 0,
            cholesterol: 65,
            sodium: 800,
            potassium: 300,
            vitaminA: 10,
            vitaminC: 10,
            calcium: 5,
            iron: 4
        }
    },
    {
        id: 27,
        name: "Kaju Roll 250 Grms",
        description: "Serves 1 | Roll Of Happiness Made With Premium Quality Cashews,Khoya And Sugar That Is Perfect For Treating Yourself To A Luxurious Dessert",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/13/e7443c07-2373-487e-aa6d-c3dbd41e0003_46112c61-89ff-49fd-afca-bdee9996cc84.jpg",
        price: 342.0,
        type: "veg",
        rating: "3.8",
        nutrition: {
            calories: 780,
            protein: 10,
            carbs: 110,
            sugars: 95,
            fiber: 2,
            fat: 35,
            saturatedFat: 15,
            transFat: 0,
            cholesterol: 50,
            sodium: 50,
            potassium: 300,
            vitaminA: 4,
            vitaminC: 2,
            calcium: 12,
            iron: 5
        }
    },
    {
        id: 24,
        name: "Katli Kaju 250 Grms",
        description: "Serves 1 | Terrifically Smooth, Thin, And Melt In Your Mouth Sweet Made From Premium Cashew Nut,Sugar And Pure Ghee.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/13/536157a4-7b77-496f-a590-431ca8ba6ad5_4c958ef3-8426-45af-9a45-ee21e40c5797.jpg",
        price: 315.0,
        type: "veg",
        rating: "3.9",
        nutrition: {
            calories: 850,
            protein: 12,
            carbs: 120,
            sugars: 100,
            fiber: 1,
            fat: 40,
            saturatedFat: 20,
            transFat: 0,
            cholesterol: 60,
            sodium: 40,
            potassium: 250,
            vitaminA: 5,
            vitaminC: 2,
            calcium: 15,
            iron: 4
        }
    },
    {
        id: 23,
        name: "Laddu Motichur 250 Grms",
        description: "Serves 1 | Indulge In The Heavenly Tiny Drops Of Chickpea Flour Which Are Deep Fried And Mixed With A Sugar Syrup And Shaped",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/yiorptxch5i1mymjkg9t",
        price: 194.0,
        type: "veg",
        rating: "4.8",
        nutrition: {
            calories: 600,
            protein: 8,
            carbs: 90,
            sugars: 75,
            fiber: 3,
            fat: 25,
            saturatedFat: 12,
            transFat: 0,
            cholesterol: 20,
            sodium: 100,
            potassium: 200,
            vitaminA: 3,
            vitaminC: 0,
            calcium: 10,
            iron: 3
        }
    },
    {
        id: 19,
        name: "Anjeer Roll 250 Grms",
        description: "Serves 1 | A Fig Roll,This Is An Indian Sweet Made With Figs,Dates And Nuts",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/8/5910b5d2-66ff-43e3-8427-de137f8bbeec_8e00f517-a809-441d-ad7e-22b96f3bbcad.jpg",
        price: 342.0,
        type: "veg",
        rating: "4.5",
        nutrition: {
            calories: 750,
            protein: 6,
            carbs: 115,
            sugars: 90,
            fiber: 4,
            fat: 30,
            saturatedFat: 10,
            transFat: 0,
            cholesterol: 10,
            sodium: 30,
            potassium: 350,
            vitaminA: 2,
            vitaminC: 2,
            calcium: 10,
            iron: 4
        }
    },
    {
        id: 20,
        name: "Jilebi 250 Grms",
        description: "Serves 1 | Batter Typically Made With All-Purpose Flour, Yogurt,Water,Shaped Into A Circular Shape Which Is Soaked In A Sugar Syrup Flavoured",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/13/f3ff8867-519b-4fd6-aa1c-1ef5b626b818_85bc038c-8938-4ea5-b61c-800d17f29aaa.jpg",
        price: 194.0,
        type: "veg",
        rating: "4.4",
        nutrition: {
            calories: 550,
            protein: 5,
            carbs: 85,
            sugars: 75,
            fiber: 1,
            fat: 25,
            saturatedFat: 8,
            transFat: 0,
            cholesterol: 10,
            sodium: 50,
            potassium: 150,
            vitaminA: 2,
            vitaminC: 0,
            calcium: 8,
            iron: 2
        }
    },
    {
        id: 21,
        name: "Mysoorpa Real 250 Grms",
        description: "Serves 1 | An Irresistible Blend Of Delicious Dessert Made With Chick Pea Flour (Besan) And Melted Ghee That Melts In Your Mouth",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/13/f23b86a7-34ce-48b0-a253-1fd7fd097844_b51f670b-8a8b-48b4-b29d-6dc0baacfd0f.jpg",
        price: 194.0,
        type: "veg",
        rating: "4.0",
        nutrition: {
            calories: 700,
            protein: 7,
            carbs: 90,
            sugars: 65,
            fiber: 3,
            fat: 35,
            saturatedFat: 15,
            transFat: 0,
            cholesterol: 60,
            sodium: 40,
            potassium: 250,
            vitaminA: 2,
            vitaminC: 0,
            calcium: 8,
            iron: 3
        }
    },
    {
        id: 22,
        name: "Halwa Badam 250 Grms",
        description: "Serves 1 | Pure And Delightful Badam Delight Made With Ground Almonds, Sugar, Ghee, Cardamoms And Saffron",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/nwytd5sufduzaueok1uo",
        price: 285.0,
        type: "veg",
        rating: "5.0",
        nutrition: {
            calories: 800,
            protein: 10,
            carbs: 70,
            sugars: 60,
            fiber: 5,
            fat: 50,
            saturatedFat: 20,
            transFat: 0,
            cholesterol: 30,
            sodium: 30,
            potassium: 350,
            vitaminA: 5,
            vitaminC: 0,
            calcium: 15,
            iron: 4
        }
    },
    {
        id: 25,
        name: "Wonder Women Fruit Bowl",
        description: "A combinations of fruits to get glowing skin and to rejuvenate your body | new | chef's special | | vegan | apple + kiwi + Mango + pomegranate + muskmelon + banana + papaya + dried blueberry + dried apricot",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/cd7668522904b38902b1568add7792fb",
        price: 280.0,
        type: "veg",
        rating: "4.5",
        nutrition: {
            calories: 250,
            protein: 3,
            carbs: 65,
            sugars: 35,
            fiber: 7,
            fat: 2,
            saturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
            sodium: 20,
            potassium: 400,
            vitaminA: 15,
            vitaminC: 80,
            calcium: 5,
            iron: 2
        }
    },
    {
        id: 26,
        name: "Special Milk Cake 250 Grms",
        description: "Serves 1 | A Traditional Indian Sweet Made With Milk, Sugar, And Lemon Juice Or Vinegar",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/13/9c0371e3-5c5f-4a4b-b116-c91d51ca8f67_04451873-77d9-44d9-9dcc-9f4afe80919b.jpg",
        price: 194.0,
        type: "veg",
        rating: "4.9",
        nutrition: {
            calories: 500,
            protein: 8,
            carbs: 75,
            sugars: 60,
            fiber: 1,
            fat: 22,
            saturatedFat: 12,
            transFat: 0,
            cholesterol: 70,
            sodium: 40,
            potassium: 200,
            vitaminA: 6,
            vitaminC: 0,
            calcium: 15,
            iron: 3
        }
    },
    {
        id: 28,
        name: "Mini Jamoon 250 Grms",
        description: "Serves 1 | Mini Version Of The Forever Loved Gulab Jamoon Is A Mouth Watering Sweet Balls Of Thickened Milk Flour,Deep-Fried In Ghee",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/13/82174152-7670-4b57-b484-eb01c694fcad_a9803530-a383-41aa-91e5-e6fe813e0157.jpg",
        price: 194.0,
        type: "veg",
        rating: "4.1",
        nutrition: {
            calories: 650,
            protein: 6,
            carbs: 90,
            sugars: 70,
            fiber: 2,
            fat: 35,
            saturatedFat: 15,
            transFat: 0,
            cholesterol: 60,
            sodium: 50,
            potassium: 250,
            vitaminA: 3,
            vitaminC: 0,
            calcium: 10,
            iron: 4
        }
    },
    {
        id: 30,
        name: "4 Crispy Chicken Tacos at 85 each",
        description: "(SAVE UPTO Rs.56 )Combo of 4 delicious Crispy Chicken Tacos filled with goodness of flavourful creamy sauces.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/3/11/455379b5-071a-4e89-b7c9-b93e12099e3b_e1bc924d-59a1-47c1-b20a-796e4290cebe.png",
        price: 340.0,
        type: "Non Veg",
        rating: "4.0",
        nutrition: {
            calories: 1600,
            protein: 32,
            carbs: 144,
            sugars: 20,
            fiber: 10,
            fat: 80,
            saturatedFat: 30,
            transFat: 0,
            cholesterol: 120,
            sodium: 1600,
            potassium: 500,
            vitaminA: 15,
            vitaminC: 10,
            calcium: 20,
            iron: 8
        }
    },
    {
        id: 33,
        name: "4 Crunchy Tacos Mexican Chicken at 85 each",
        description: "(SAVE UPTO Rs.136 )Combo of 4 delicious Crunchy Tacos filled with goodness of Mexican Chicken, Veggies & flavourful creamy sauces. Upgrade options available.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/e0e4c25cad3de957363633a585f198c7",
        price: 340.0,
        type: "Non Veg",
        rating: "3.9",
        nutrition: {
            calories: 1400,
            protein: 30,
            carbs: 130,
            sugars: 22,
            fiber: 8,
            fat: 70,
            saturatedFat: 28,
            transFat: 0,
            cholesterol: 110,
            sodium: 1500,
            potassium: 450,
            vitaminA: 10,
            vitaminC: 12,
            calcium: 18,
            iron: 7
        }
    },
    {
        id: 34,
        name: "4 Crispy Chicken Wraps at 95 each",
        description: "(SAVE UPTO Rs.16 )Combo of 4 Crispy Chicken Wraps made of flavourful warm tortilla loaded with crispy chicken strip and bold flavourful sauces",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/a8ac36aa522be3a2044f2ba7f26a0b10",
        price: 180.0,
        type: "Non Veg",
        rating: "4.1",
        nutrition: {
            calories: 1200,
            protein: 28,
            carbs: 100,
            sugars: 18,
            fiber: 7,
            fat: 60,
            saturatedFat: 25,
            transFat: 0,
            cholesterol: 100,
            sodium: 1200,
            potassium: 400,
            vitaminA: 12,
            vitaminC: 8,
            calcium: 15,
            iron: 6
        }
    },
    {
        id: 31,
        name: "Mango Smoothie Bowl",
        description: "Fresh made with pure fruits and natural | no added sugar | | vegan |choice of vegan milk + mango + banana + dates grinded together and topped with pomegranate + banana + coconut flakes + chia seed.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/682dde096ef512c2e380a29fc366aec8",
        price: 380.0,
        type: "Non Veg",
        rating: "3.8",
        nutrition: {
            calories: 400,
            protein: 5,
            carbs: 80,
            sugars: 50,
            fiber: 10,
            fat: 10,
            saturatedFat: 4,
            transFat: 0,
            cholesterol: 0,
            sodium: 30,
            potassium: 600,
            vitaminA: 30,
            vitaminC: 80,
            calcium: 10,
            iron: 2
        }
    },
    {
        id: 29,
        name: "2 Crispy Chicken Wrap + 2 Sriracha Burrito Chicken at 390",
        description: "(SAVE UPTO Rs.150) Combo of 2 Chicken Habanero Burrito and 2 Crispy Chicken Wrap",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/bc0dee78b8fd92bf7418cb4287820e9f",
        price: 390.0,
        type: "Non Veg",
        rating: "4.4",
        nutrition: {
            calories: 1600,
            protein: 40,
            carbs: 140,
            sugars: 20,
            fiber: 12,
            fat: 80,
            saturatedFat: 30,
            transFat: 0,
            cholesterol: 160,
            sodium: 1800,
            potassium: 600,
            vitaminA: 20,
            vitaminC: 15,
            calcium: 25,
            iron: 10
        }
    },
    {
        id: 36,
        name: "4 Crispy Potato Wraps at 64 each",
        description: "(SAVE UPTO Rs.20 )Combo of 4 Crispy Potato Wraps made of flavourful warm tortilla loaded with crispy potato bites and bold flavourful sauces",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/9a20d92a8a14f37bcbab051aa8cb6195",
        price: 256.0,
        type: "veg",
        rating: "4.9",
        nutrition: {
            calories: 1200,
            protein: 10,
            carbs: 150,
            sugars: 15,
            fiber: 8,
            fat: 60,
            saturatedFat: 25,
            transFat: 0,
            cholesterol: 0,
            sodium: 1000,
            potassium: 450,
            vitaminA: 5,
            vitaminC: 10,
            calcium: 15,
            iron: 5
        }
    },
    {
        id: 38,
        name: "2 Crunchy Taco Veg + 2 Crispy Potato Taco at 59 each",
        description: "(SAVE UPTO Rs.120 )Combo of 2 Crunchy Taco Bean and 2 Crispy Potato Taco, filled with goodness of flavourful creamy sauces.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/3/11/76b0fc0f-6331-41bd-94b2-b7a4b9fcf31a_fa46fb3b-e3ef-42ef-8fec-092ee1e960b0.png",
        price: 236.0,
        type: "veg",
        rating: "4.2",
        nutrition: {
            calories: 800,
            protein: 12,
            carbs: 90,
            sugars: 18,
            fiber: 9,
            fat: 40,
            saturatedFat: 18,
            transFat: 0,
            cholesterol: 0,
            sodium: 800,
            potassium: 400,
            vitaminA: 10,
            vitaminC: 15,
            calcium: 20,
            iron: 4
        }
    },
    {
        id: 37,
        name: "4 Habanero Burrito Veg at 69 each",
        description: "(SAVE UPTO Rs. 184 )Combo of 4 Veg Sriracha Burritos made of flavourful warm tortilla filled with delicious fajita veg toppings and spicy sriracha sauce",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/146e5cdf28175082a1cacaea33635e3f",
        price: 276.0,
        type: "veg",
        rating: "4.5",
        nutrition: {
            calories: 1200,
            protein: 20,
            carbs: 100,
            sugars: 20,
            fiber: 12,
            fat: 50,
            saturatedFat: 18,
            transFat: 0,
            cholesterol: 0,
            sodium: 1000,
            potassium: 500,
            vitaminA: 10,
            vitaminC: 15,
            calcium: 25,
            iron: 6
        }
    },
    {
        id: 32,
        name: "2 Crunchy Taco Chicken + 2 Crispy Chicken Taco at 85 each",
        description: "(SAVE UPTO Rs.96 )Combo of 2 Crunchy Taco Mexican Chicken and 2 Crispy Chicken Taco, filled with goodness of flavourful creamy sauces.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/3/11/cb743678-be6f-4e5c-851d-146cb8eac86d_a4f921fe-f24b-4357-b19f-bfbd24dabf8c.png",
        price: 340.0,
        type: "Non Veg",
        rating: "4.7",
        nutrition: {
            calories: 1400,
            protein: 34,
            carbs: 130,
            sugars: 24,
            fiber: 10,
            fat: 70,
            saturatedFat: 28,
            transFat: 0,
            cholesterol: 130,
            sodium: 1600,
            potassium: 500,
            vitaminA: 15,
            vitaminC: 12,
            calcium: 20,
            iron: 7
        }
    },
    {
        id: 35,
        name: "2 Crispy Potato Wrap + 2 Habanero Burrito Veg at 266",
        description: "(SAVE UPTO Rs. 102 )Combo of 2 Veg Sriracha Burrito and 2 Crispy Potato Wrap",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/3/11/13a91ff8-79ce-424a-b437-2901cf96945d_e911466e-e885-4a76-b7c4-0508ab6e3ccc.png",
        price: 266.0,
        type: "veg",
        rating: "4.9",
        nutrition: {
            calories: 1400,
            protein: 22,
            carbs: 140,
            sugars: 20,
            fiber: 12,
            fat: 70,
            saturatedFat: 28,
            transFat: 0,
            cholesterol: 0,
            sodium: 1200,
            potassium: 600,
            vitaminA: 12,
            vitaminC: 18,
            calcium: 25,
            iron: 6
        }
    },
    {
        id: 43,
        name: "Pizza Party for 4 (Veg) @Rs. 180 Off",
        description: "Meal for 4: Regular Veg Extravaganza + Regular Indi Tandoori Paneer + Regular Farmhouse + Regular Veggie Paradise",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/3/4/769c1543-78a6-415e-a7c1-a158dcfe7be9_a994c743-205b-4a67-abce-e5507ca2fe56_compressed",
        price: 999.0,
        type: "veg",
        rating: "4.9",
        nutrition: {
            calories: 4800,
            protein: 80,
            carbs: 640,
            sugars: 50,
            fiber: 40,
            fat: 200,
            saturatedFat: 80,
            transFat: 0,
            cholesterol: 120,
            sodium: 2000,
            potassium: 1500,
            vitaminA: 50,
            vitaminC: 25,
            calcium: 40,
            iron: 20
        }
    },
    {
        id: 40,
        name: "Cheese Volcano BBQ Chicken",
        description: "Centre loaded with Molten Cheese & topped with Pepper BBQ Chicken *Contains non-edible container under the Pizza",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/7/4/bb8bf7b5-d084-4690-893e-ea5af460ad5d_fd69db19-9923-4ab7-936c-e2b1300a9b25.jpg",
        price: 349.0,
        type: "Non Veg",
        rating: "3.9",
        nutrition: {
            calories: 1200,
            protein: 40,
            carbs: 130,
            sugars: 12,
            fiber: 8,
            fat: 70,
            saturatedFat: 30,
            transFat: 0,
            cholesterol: 100,
            sodium: 1500,
            potassium: 500,
            vitaminA: 20,
            vitaminC: 10,
            calcium: 30,
            iron: 6
        }
    },
    {
        id: 39,
        name: "Cheese Volcano Veg Paradise",
        description: "Centre loaded with Molten Cheese & topped with Golden Corn, Black Olives, Capsicum & Red Paprika *Contains non-edible container under the Pizza",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/7/4/3e08f33d-98b7-41d2-acca-182da98e80f4_dd0b2e67-2a47-4a5e-b906-63e1277e7fa2.jpg",
        price: 299.0,
        type: "veg",
        rating: "4.8",
        nutrition: {
            calories: 1000,
            protein: 25,
            carbs: 120,
            sugars: 10,
            fiber: 9,
            fat: 50,
            saturatedFat: 20,
            transFat: 0,
            cholesterol: 0,
            sodium: 1200,
            potassium: 400,
            vitaminA: 25,
            vitaminC: 20,
            calcium: 30,
            iron: 5
        }
    },
    {
        id: 48,
        name: "Cheese Volcano Blazing Chicken",
        description: "Centre loaded with Molten Cheese & topped with Chicken Keema & Red Paprika with our spicy Peri Peri Sauce *Contains non-edible container under the Pizza",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/7/4/e0d6d213-d5ac-45a7-b53f-d6c836d53659_33957602-94cc-4a32-9a21-6b65d35815fc.jpg",
        price: 349.0,
        type: "Non Veg",
        rating: "3.8",
        nutrition: {
            calories: 1200,
            protein: 35,
            carbs: 130,
            sugars: 14,
            fiber: 8,
            fat: 70,
            saturatedFat: 30,
            transFat: 0,
            cholesterol: 120,
            sodium: 1600,
            potassium: 500,
            vitaminA: 20,
            vitaminC: 12,
            calcium: 30,
            iron: 7
        }
    },
    {
        id: 46,
        name: "Cheese Volcano Farmhouse",
        description: "Centre loaded with Molten Cheese & topped with Onion, Capsicum, Tomato & Grilled Mushroom *Contains non-edible container under the Pizza",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/7/4/4e30b1ff-dbe8-41d3-b083-d46b9d742ffc_636d161e-7f34-4371-b63c-bf9e3d091a0f.jpg",
        price: 299.0,
        type: "veg",
        rating: "4.0",
        nutrition: {
            calories: 1000,
            protein: 25,
            carbs: 110,
            sugars: 15,
            fiber: 10,
            fat: 50,
            saturatedFat: 20,
            transFat: 0,
            cholesterol: 0,
            sodium: 1200,
            potassium: 450,
            vitaminA: 20,
            vitaminC: 15,
            calcium: 30,
            iron: 5
        }
    },
    {
        id: 41,
        name: "Cheese Volcano Chicken Delight",
        description: "Centre loaded with Molten Cheese & topped with Pepper BBQ Chicken & Golden Corn *Contains non-edible container under the Pizza",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/7/4/ec91a814-b0f9-4911-b972-3c2a3583c684_d8de24fd-5109-4870-bf74-66f9ebb4ace5.jpg",
        price: 349.0,
        type: "Non Veg",
        rating: "4.5",
        nutrition: {
            calories: 1200,
            protein: 40,
            carbs: 120,
            sugars: 12,
            fiber: 8,
            fat: 60,
            saturatedFat: 25,
            transFat: 0,
            cholesterol: 100,
            sodium: 1500,
            potassium: 500,
            vitaminA: 20,
            vitaminC: 12,
            calcium: 30,
            iron: 6
        }
    },
    {
        id: 42,
        name: "Chicken Burger",
        description: "Crumb Fried Chicken Patty Topped With Lots Of In House Sauces And Lettuce.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/a8ac36aa522be3a2044f2ba7f26a0b10",
        price: 180.0,
        type: "Non Veg",
        rating: "4.1",
        nutrition: {
            calories: 600,
            protein: 25,
            carbs: 60,
            sugars: 10,
            fiber: 5,
            fat: 30,
            saturatedFat: 10,
            transFat: 0,
            cholesterol: 80,
            sodium: 800,
            potassium: 300,
            vitaminA: 10,
            vitaminC: 5,
            calcium: 15,
            iron: 4
        }
    },
    {
        id: 47,
        name: "Cheese Volcano Double Chicken",
        description: "Centre loaded with Molten Cheese & topped with Pepper BBQ Chicken & Peri Peri Chicken. *Contains non-edible container under the Pizza",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/7/4/a842381d-5d56-4a1e-99b8-4594170ae2c1_6d79c2a4-5aec-4067-acea-0afdfd875830.jpg",
        price: 349.0,
        type: "Non Veg",
        rating: "4.2",
        nutrition: {
            calories: 1300,
            protein: 45,
            carbs: 140,
            sugars: 14,
            fiber: 8,
            fat: 70,
            saturatedFat: 30,
            transFat: 0,
            cholesterol: 120,
            sodium: 1600,
            potassium: 500,
            vitaminA: 25,
            vitaminC: 10,
            calcium: 30,
            iron: 7
        }
    },
    {
        id: 45,
        name: "Corn & Cheese Volcano",
        description: "Centre loaded with Molten Cheese & topped with juicy Golden Corn *Contains non-edible container under the Pizza",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/7/4/375ae4df-de00-4235-97c5-3de32ebd969c_c7ea4a4e-86a9-467b-a42d-13e058670d28.jpg",
        price: 299.0,
        type: "veg",
        rating: "4.5",
        nutrition: {
            calories: 1000,
            protein: 20,
            carbs: 110,
            sugars: 15,
            fiber: 10,
            fat: 50,
            saturatedFat: 20,
            transFat: 0,
            cholesterol: 0,
            sodium: 1200,
            potassium: 450,
            vitaminA: 20,
            vitaminC: 15,
            calcium: 30,
            iron: 5
        }
    },
    {
        id: 44,
        name: "Cheese Volcano Peppy Paneer",
        description: "Centre loaded with Molten Cheese & topped with peppy Paneer, Capsicum & Red Paprika *Contains non-edible container under the Pizza",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/7/4/3ab84285-8164-4447-b534-f371913491c6_f91a0f02-a155-4a2a-8567-ae9d56ec5b2b.jpg",
        price: 299.0,
        type: "veg",
        rating: "4.9",
        nutrition: {
            calories: 1000,
            protein: 22,
            carbs: 110,
            sugars: 12,
            fiber: 9,
            fat: 50,
            saturatedFat: 22,
            transFat: 0,
            cholesterol: 0,
            sodium: 1200,
            potassium: 450,
            vitaminA: 20,
            vitaminC: 15,
            calcium: 35,
            iron: 6
        }
    },
    {
        id: 50,
        name: "Bucket for Two",
        description: "Flat Rs.115 off on combo of 2pc Hot & Crispy",
        imageUrl: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xs/D-PR00000892.jpg?ver=49.63",
        price: 599.0,
        type: "Non Veg",
        rating: "4.3",
        nutrition: {
            calories: 1400,
            protein: 50,
            carbs: 120,
            sugars: 10,
            fiber: 5,
            fat: 80,
            saturatedFat: 30,
            transFat: 1,
            cholesterol: 150,
            sodium: 2000,
            potassium: 600,
            vitaminA: 15,
            vitaminC: 5,
            calcium: 10,
            iron: 10
        }
    },
    {
        id: 49,
        name: "All in One Bucket",
        description: "1 Leg, 1 Hot & Crispy, 2 Wings, 2 Strips, 1 Zinger Fillet",
        imageUrl: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/md/D-PR00002340.jpg?ver=49.63",
        price: 548.0,
        type: "Non Veg",
        rating: "4.7",
        nutrition: {
            calories: 1600,
            protein: 55,
            carbs: 130,
            sugars: 12,
            fiber: 6,
            fat: 90,
            saturatedFat: 35,
            transFat: 1,
            cholesterol: 180,
            sodium: 2200,
            potassium: 700,
            vitaminA: 20,
            vitaminC: 6,
            calcium: 12,
            iron: 12
        }
    },
    {
        id: 51,
        name: "Stay Home Bucket",
        description: "Save 21% on 4 Hot & Crispy, 6 Wings, 2 Peri Strips",
        imageUrl: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xs/D-PR00002169.jpg?ver=49.63",
        price: 788.0,
        type: "Non Veg",
        rating: "4.5",
        nutrition: {
            calories: 2000,
            protein: 70,
            carbs: 150,
            sugars: 15,
            fiber: 8,
            fat: 110,
            saturatedFat: 40,
            transFat: 2,
            cholesterol: 200,
            sodium: 2500,
            potassium: 800,
            vitaminA: 25,
            vitaminC: 8,
            calcium: 15,
            iron: 15
        }
    },
    {
        id: 52,
        name: "Paneer Tikka",
        description: "India, Veg",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/7/12/9d69b27a-aca8-4072-91f1-1b5213d6c961_39e3151e-79f3-4f6b-b374-fa33dbe2c15f.jpg",
        price: 250.0,
        type: "Veg",
        rating: 4.7,
        nutrition: {
            calories: 280,
            protein: 18,
            carbs: 10,
            sugars: 4,
            fiber: 2,
            fat: 20,
            saturatedFat: 10,
            transFat: 0,
            cholesterol: 60,
            sodium: 600,
            potassium: 350,
            vitaminA: 15,
            vitaminC: 10,
            calcium: 25,
            iron: 15
        }
    },
    {
        id: 54,
        name: "Kallan Milagu Varuval",
        description: "Veg and Spicy",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/d77183606a5ba2abfe544093e327039a",
        price: 254.0,
        type: "Veg",
        rating: 4.7,
        nutrition: {
            calories: 320,
            protein: 15,
            carbs: 12,
            sugars: 5,
            fiber: 4,
            fat: 25,
            saturatedFat: 12,
            transFat: 1,
            cholesterol: 0,
            sodium: 650,
            potassium: 400,
            vitaminA: 20,
            vitaminC: 15,
            calcium: 20,
            iron: 18
        }
    },
    {
        id: 53,
        name: "Gobi 65",
        description: "Bestseller",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/7/12/8df98d78-0dc9-41e4-ad5d-f4ba02e6a077_7767e9a4-3714-473d-83df-4e42810b6f63.jpg",
        price: 218.0,
        type: "Veg",
        rating: 4.7,
        nutrition: {
            calories: 250,
            protein: 10,
            carbs: 20,
            sugars: 6,
            fiber: 3,
            fat: 15,
            saturatedFat: 8,
            transFat: 0,
            cholesterol: 0,
            sodium: 700,
            potassium: 300,
            vitaminA: 10,
            vitaminC: 25,
            calcium: 15,
            iron: 10
        }
    },
    {
        id: 56,
        name: "Chilli Cheese Sandwich + Side + Coke",
        description: "Enjoy your fav Hotseller with a choice of cooke and drink",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/9020a32adc2b5fc28ac6ed497ea14a3a",
        price: 389.0,
        type: "Veg",
        rating: 4.3,
        nutrition: {
            calories: 850,
            protein: 20,
            carbs: 115,
            sugars: 30,
            fiber: 8,
            fat: 30,
            saturatedFat: 12,
            transFat: 1,
            cholesterol: 60,
            sodium: 1500,
            potassium: 300,
            vitaminA: 20,
            vitaminC: 25,
            calcium: 20,
            iron: 15
        }
    },
    {
        id: 57,
        name: "Delhi Tikki Sandwich + Side + Coke",
        description: "Enjoy your favourite Grills Sandwich",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/3b1bb2e4ab7a6f145d675e811b4ee0a3",
        price: 290.0,
        type: "Veg",
        rating: 3.8,
        nutrition: {
            calories: 700,
            protein: 12,
            carbs: 95,
            sugars: 20,
            fiber: 6,
            fat: 25,
            saturatedFat: 8,
            transFat: 0,
            cholesterol: 40,
            sodium: 1200,
            potassium: 250,
            vitaminA: 15,
            vitaminC: 20,
            calcium: 15,
            iron: 12
        }
    },
    {
        id: 55,
        name: "Great American BBQ Sandwich + Side + Coke",
        description: "Enjoy your favourite Hotseller sub with a choice of cookie",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/b4e32b37ea2c71cfc7b28f885aa668fe",
        price: 429.0,
        type: "Non Veg",
        rating: 4.0,
        nutrition: {
            calories: 950,
            protein: 25,
            carbs: 120,
            sugars: 25,
            fiber: 7,
            fat: 35,
            saturatedFat: 15,
            transFat: 1,
            cholesterol: 80,
            sodium: 1600,
            potassium: 350,
            vitaminA: 20,
            vitaminC: 15,
            calcium: 25,
            iron: 18
        }
    },
    {
        id: 58,
        name: "Combo for 1 Non-Veg",
        description: "Serves 1 | Combo for one (Rice/Noodle Bowl with choice of Non-Veg Gravy, Non- Veg Momos & Drinks)",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/440c06ace44b931b729d9b6a090aba07",
        price: 379.0,
        type: "Non Veg",
        rating: 4.0,
        nutrition: {
            calories: 1100,
            protein: 30,
            carbs: 140,
            sugars: 20,
            fiber: 8,
            fat: 50,
            saturatedFat: 15,
            transFat: 2,
            cholesterol: 80,
            sodium: 2000,
            potassium: 500,
            vitaminA: 15,
            vitaminC: 25,
            calcium: 10,
            iron: 20
        }
    },
    {
        id: 59,
        name: "Hunan Paneer Dry",
        description: "Serves 1 | (Spicy) Cubes Of Paneer, Onion, Capsicum Tossed With Spicy & Savory flavors of Hunan Sauce.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/7/a05bf8ea-ee68-4fd8-be01-1ac10f940fa5_c8e1a500-cd36-4f60-a771-1e5cf22e73c4.jpg_compressed",
        price: 149.0,
        type: "Veg",
        rating: 4.2,
        nutrition: {
            calories: 320,
            protein: 15,
            carbs: 20,
            sugars: 10,
            fiber: 5,
            fat: 20,
            saturatedFat: 10,
            transFat: 0,
            cholesterol: 50,
            sodium: 800,
            potassium: 300,
            vitaminA: 10,
            vitaminC: 20,
            calcium: 15,
            iron: 12
        }
    },
    {
        id: 60,
        name: "Combo for 1 Veg",
        description: "Serves 1 | Combo for one (Rice/Noodle Bowl with choice of Veg Gravy, Veg Momos & Drinks)",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/3e4f7ca32bf517b390f1cb3205b892e4",
        price: 359.0,
        type: "Veg",
        rating: 3.9,
        nutrition: {
            calories: 1050,
            protein: 20,
            carbs: 130,
            sugars: 15,
            fiber: 10,
            fat: 40,
            saturatedFat: 12,
            transFat: 1,
            cholesterol: 30,
            sodium: 1800,
            potassium: 400,
            vitaminA: 15,
            vitaminC: 30,
            calcium: 12,
            iron: 18
        }
    },
    {
        id: 62,
        name: "Grilled Barbeque Chicken Rice Bowl (Regular)",
        description: "Serves 1 | Fresh cilantro rice and everything nice. Comes with your favourite toppings, fajita veggies like bell peppers and onions.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/850b109187edc3968df3c00cc8b9c825",
        price: 309.0,
        type: "Non Veg",
        rating: 4.4,
        nutrition: {
            calories: 600,
            protein: 35,
            carbs: 65,
            sugars: 8,
            fiber: 6,
            fat: 20,
            saturatedFat: 6,
            transFat: 0,
            cholesterol: 90,
            sodium: 800,
            potassium: 600,
            vitaminA: 15,
            vitaminC: 20,
            calcium: 12,
            iron: 15
        }
    },
    {
        id: 61,
        name: "Barbeque Paneer Rice Bowl (Regular)",
        description: "Serves 1 | Fresh cilantro rice and everything nice. Comes with your favourite toppings, fajita veggies like bell peppers and onions, pico de gallo.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/f590ac3a24773c350ccc5e8dcfcbd808",
        price: 309.0,
        type: "Veg",
        rating: 4.6,
        nutrition: {
            calories: 650,
            protein: 20,
            carbs: 80,
            sugars: 12,
            fiber: 8,
            fat: 25,
            saturatedFat: 10,
            transFat: 0,
            cholesterol: 60,
            sodium: 900,
            potassium: 500,
            vitaminA: 20,
            vitaminC: 25,
            calcium: 15,
            iron: 18
        }
    },
    {
        id: 63,
        name: "Crispy Peri Peri Chicken Rice Bowl (Regular)",
        description: "Serves 1 | Fresh cilantro rice and everything nice. Comes with your favourite toppings, fajita veggies like bell peppers and onions.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/e27ed32be7247b7a1d0b57cb12e64efd",
        price: 309.0,
        type: "Non Veg",
        rating: 4.3,
        nutrition: {
            calories: 620,
            protein: 30,
            carbs: 70,
            sugars: 10,
            fiber: 7,
            fat: 22,
            saturatedFat: 7,
            transFat: 0,
            cholesterol: 85,
            sodium: 850,
            potassium: 550,
            vitaminA: 18,
            vitaminC: 22,
            calcium: 13,
            iron: 16
        }
    },
    {
        id: 64,
        name: "Egg Biryani",
        description: "Indian",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/zja6wlwqkrvna2aancm3",
        price: 179.0,
        type: "Non Veg",
        rating: 4.2,
        nutrition: {
            calories: 650,
            protein: 20,
            carbs: 85,
            sugars: 7,
            fiber: 5,
            fat: 25,
            saturatedFat: 6,
            transFat: 0,
            cholesterol: 240,
            sodium: 800,
            potassium: 500,
            vitaminA: 10,
            vitaminC: 5,
            calcium: 8,
            iron: 15
        }
    },
    {
        id: 65,
        name: "Chilli Fish",
        description: "Seafood",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/4/16/242e9643-e7ac-426a-8997-71db9f829c30_71704ced-4599-42a9-962f-784b6e3af5a3.jpg",
        price: 240.0,
        type: "Non Veg",
        rating: 4.2,
        nutrition: {
            calories: 500,
            protein: 30,
            carbs: 40,
            sugars: 8,
            fiber: 3,
            fat: 25,
            saturatedFat: 5,
            transFat: 0,
            cholesterol: 80,
            sodium: 950,
            potassium: 400,
            vitaminA: 15,
            vitaminC: 15,
            calcium: 10,
            iron: 12
        }
    },
    {
        id: 66,
        name: "Vanjaram Fish",
        description: "Seafood",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/4/16/fd549b37-1b92-4296-9aab-848b06df1c05_30b9f752-f6ac-4488-b847-aece406822f7.jpeg",
        price: 200.0,
        type: "Non Veg",
        rating: 4.4,
        nutrition: {
            calories: 450,
            protein: 25,
            carbs: 20,
            sugars: 4,
            fiber: 2,
            fat: 25,
            saturatedFat: 4,
            transFat: 0,
            cholesterol: 70,
            sodium: 750,
            potassium: 300,
            vitaminA: 8,
            vitaminC: 5,
            calcium: 6,
            iron: 10
        }
    }
];

export default Datas;
